<?php
$this->headTitle('Downloads');

$this->mainMenu()->setActiveItemId('downloads');

$this->pageBreadcrumbs()->setItems(array(
            'Home'=>$this->url('home'),
            'Downloads'=>$this->url('download', ['action'=>'index'])
            ));
?>

<h1>Downloads</h1>

<ul>
    <li>
        <a href="<?php echo $this->url("download", ['action'=>'file'], 
                ['query'=>['name'=>'sample.txt']]); ?>">
            sample.txt
        </a>
    </li>
</ul>