<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Internationalization & Localization Demo')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-2.2.4.min.js'))
        ?>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <!-- Page header -->
                <div class="col-md-4">
                    <div class="app-caption"><?= $this->translate('i18n Demo') ?></div>
                </div>                
            </div>
            <div class="row">
                <div class="col-md-12">
                    <!-- Navigation bar -->
                    <?php
                    // Initialize navbar items
                    $this->mainMenu()->setItems([
                        [
                            'id' => 'home',
                            'label' => $this->translate('Home'),
                            'link' => $this->url('home'),
                            'icon' => 'glyphicon-home',
                        ],
                        [
                            'id' => 'about',
                            'label' => $this->translate('About'),
                            'link' => $this->url('about'),
                            'icon' => 'glyphicon-info-sign',
                        ],
                        [
                            'id' => 'language',
                            'label' => $this->translate('Language'),
                            'icon' => 'glyphicon-globe',
                            'dropdown' => [
                              [
                                'id' => 'en',
                                'label' => 'English (EN)',
                                'link' => $this->url('application', ['action'=>'set-language', 'id'=>'en_US'])
                              ],
                              [
                                'id' => 'ru',
                                'label' => 'Russian (RU)',
                                'link' => $this->url('application', ['action'=>'set-language', 'id'=>'ru_RU'])
                              ],
                              [
                                'id' => 'es',
                                'label' => 'Spanish (ES)',
                                'link' => $this->url('application', ['action'=>'set-language', 'id'=>'es_ES'])
                              ]
                            ]     
                        ],
                    ]);

                    // Check if the activeMenuItemId passed to layout view model
                    // and if so, use it for setting active navbar item.
                    if (isset($activeMenuItemId)) {
                        $this->mainMenu()->setActiveItemId($activeMenuItemId);
                    }

                    // Render the navbar
                    echo $this->mainMenu()->render();
                    ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <!-- Breadcrumbs -->
                    <?= $this->pageBreadcrumbs()->render(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <!-- Page content placeholder -->
                    <?= $this->content; ?>
                </div>
            </div>
            <hr>
            <footer>
                <p><?= $this->translate('&copy; 2005 - 2018 by Your Company. All rights reserved.') ?></p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
