<?php
$this->headTitle('Typeahead');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home')
            ]);

$this->headScript()->appendFile('/js/typeahead.min.js', 'text/javascript');
?>

<h1>Typeahead</h1>

<p>
    Type a continent name (e.g. Africa) in the text field below:
</p>

<input type="text" class="typeahead" title="Type here"/>

<script type="text/javascript">
    
    $( document ).ready(function() {
    
        $('input.typeahead').typeahead({
            name: 'continents',
            local: 
            [
                'Africa', 
                'Antarctica',
                'Asia',
                'Europe',
                'South America', 
                'North America'            
            ]
        });
        
    });
</script>