<?php
$this->headTitle('Partial View Demo');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home')
            ]);

?>

<h1>Partial View Demo</h1>

<p>
    Below, the table of products is presented. It is rendered with the help of
    partial views.
</p>

<table class="table table-striped table-hover">
    <tr>
        <th>ID</th>
        <th>Product</th>
        <th>Price</th>
    </tr>

    <?php 
        foreach($this->products as $product) {
            echo $this->partial('application/index/table-row', ['product'=>$product]);
        }    
    ?>    
</table>