<?php
$this->headTitle('Welcome');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home')
            ]);
?>

<h1><?= $this->translate('Welcome') ?></h1>

<p>
    <?= $this->translate('This is the Internationalization &amp; Localization Demo application.') ?>
</p>

<p>
    <?= $this->translate('Current language is') ?> <?= $this->escapeHtml($this->languageId) ?>. 
    <?= $this->translate('Select a language using the <em>Language</em> item in the top navigation menu.') ?>
</p>

<ul>
    <li>
        <a href="<?php echo $this->url('contactus'); ?>"><?= $this->translate('Feedback Form') ?></a> 
        <?= $this->translate('This page shows the localized feedback form.') ?>
    </li>
</ul>

