<?php

$this->headTitle('Contact Us');

$this->mainMenu()->setActiveItemId('contactUs');

$this->pageBreadcrumbs()->setItems(array(
            'Home'=>$this->url('home'),
            'Contact Us'=>$this->url('contactus')
            ));

?>

<h1><?= $this->translate('Thank You!') ?></h1>

<p>
    <div class="alert alert-success">
        <?= $this->translate('We will respond to the E-mail address you have provided.') ?>
    </div>
</p>
