<?php $this->placeholder('content')->captureStart(); ?>

<div class="row">
    <div class="col-md-8">
    <?= $this->content; ?>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                  <h3 class="panel-title">Ads</h3>
            </div>
            <div class="panel-body">
              <strong>Zend Framework 3 Book</strong>
              <p>Learn how to create modern web applications with PHP 
              and Zend Framework 3</p>            
              <a target="_blank" href="https://github.com/olegkrivtsov/using-zend-framework-3-book">
                  Learn More
              </a>
            </div>
        </div>
    </div>
</div>

<?php 
  $this->placeholder('content')->captureEnd(); 
  echo $this->partial('layout/layout', 
          ['content'=>$this->placeholder('content')]); 
?>

