<?php
$this->headTitle('Documentation');

$this->mainMenu()->setActiveItemId('support');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Documentation'=>$this->url('doc', ['page'=>'contents']),    
]);
?>

<h1>Table of Contents</h1>

<ul>
    <li>
        <a href="<?= $this->url('doc', ['page'=>'introduction']); ?>">
            Introduction
        </a>
    </li>
    <li>
        <a href="<?= $this->url('doc', ['page'=>'install']); ?>">
            Installation
        </a>
    </li>    
</ul>