<?php
$this->headTitle('Welcome');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home')
            ]);
?>

<h1>Welcome</h1>

<p>
    This is the Role Demo application powered by Zend Framework 3. It is based on User Demo sample. 
    It demonstrates how to implement role-based access control.
</p>

<p>
    Click the <em>Sign in</em> button at the top right. To sign in, use the 
    following credentials:
    <ul>
        <li>Username: <em>admin@example.com</em></li>
        <li>Password: <em>Secur1ty</em></li>
    </ul>    
</p>

<p>
    When signed in, use the <em>Admin</em> menu at the top to manage users, roles and permissions.
</p>


